/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginAdminRouteImport } from './routes/login_.admin'
import { Route as LoginProviderRouteImport } from './routes/login_.provider'
import { Route as SignupProviderRouteImport } from './routes/signup_.provider'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginAdminRoute = LoginAdminRouteImport.update({
  id: '/login_/admin',
  path: '/login/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginProviderRoute = LoginProviderRouteImport.update({
  id: '/login_/provider',
  path: '/login/provider',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupProviderRoute = SignupProviderRouteImport.update({
  id: '/signup_/provider',
  path: '/signup/provider',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/login/admin': typeof LoginAdminRoute
  '/login/provider': typeof LoginProviderRoute
  '/signup/provider': typeof SignupProviderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/login/admin': typeof LoginAdminRoute
  '/login/provider': typeof LoginProviderRoute
  '/signup/provider': typeof SignupProviderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/login_/admin': typeof LoginAdminRoute
  '/login_/provider': typeof LoginProviderRoute
  '/signup_/provider': typeof SignupProviderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/login/admin'
    | '/login/provider'
    | '/signup/provider'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/login/admin'
    | '/login/provider'
    | '/signup/provider'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/login_/admin'
    | '/login_/provider'
    | '/signup_/provider'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  LoginAdminRoute: typeof LoginAdminRoute
  LoginProviderRoute: typeof LoginProviderRoute
  SignupProviderRoute: typeof SignupProviderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login_/admin': {
      id: '/login_/admin'
      path: '/login/admin'
      fullPath: '/login/admin'
      preLoaderRoute: typeof LoginAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login_/provider': {
      id: '/login_/provider'
      path: '/login/provider'
      fullPath: '/login/provider'
      preLoaderRoute: typeof LoginProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup_/provider': {
      id: '/signup_/provider'
      path: '/signup/provider'
      fullPath: '/signup/provider'
      preLoaderRoute: typeof SignupProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  LoginAdminRoute: LoginAdminRoute,
  LoginProviderRoute: LoginProviderRoute,
  SignupProviderRoute: SignupProviderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
